sonar.projectKey=flowboard-card-service
sonar.projectName=FlowBoard Card Service
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.test.inclusions=src/test/java/**/*.java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.junit.reportPaths=target/surefire-reports
sonar.exclusions=**/target/**,**/.mvn/**,**/mvnw,**/mvnw.cmd
sonar.coverage.exclusions=src/main/java/com/card/CardServiceApplication.java,src/main/java/com/card/client/dto/NotifyDueDateRequest.java,src/main/java/com/card/client/dto/SendNotificationRequest.java,src/main/java/com/card/config/RabbitMQConfig.java,src/main/java/com/card/config/SecurityConfig.java,src/main/java/com/card/dto/AssignCardRequest.java,src/main/java/com/card/dto/BoardStatsResponse.java,src/main/java/com/card/dto/CardActivityResponse.java,src/main/java/com/card/dto/CardResponse.java,src/main/java/com/card/dto/CreateCardRequest.java,src/main/java/com/card/dto/MoveCardRequest.java,src/main/java/com/card/dto/ReorderCardRequest.java,src/main/java/com/card/dto/SetPriorityRequest.java,src/main/java/com/card/dto/SetStatusRequest.java,src/main/java/com/card/dto/UpdateCardRequest.java,src/main/java/com/card/entity/Card.java,src/main/java/com/card/entity/CardActivity.java,src/main/java/com/card/entity/CardStatus.java,src/main/java/com/card/entity/Priority.java,src/main/java/com/card/exception/ErrorResponse.java,src/main/java/com/card/exception/GlobalExceptionHandler.java,src/main/java/com/card/repository/CardActivityRepository.java,src/main/java/com/card/repository/CardRepository.java,src/main/java/com/card/service/CardService.java,src/main/java/com/card/service/CardServiceImpl.java
sonar.issue.ignore.multicriteria=s1068dto,s1068entity,s1068exception,s1068clientdto
sonar.issue.ignore.multicriteria.s1068dto.ruleKey=java:S1068
sonar.issue.ignore.multicriteria.s1068dto.resourceKey=**/dto/**/*.java
sonar.issue.ignore.multicriteria.s1068entity.ruleKey=java:S1068
sonar.issue.ignore.multicriteria.s1068entity.resourceKey=**/entity/**/*.java
sonar.issue.ignore.multicriteria.s1068exception.ruleKey=java:S1068
sonar.issue.ignore.multicriteria.s1068exception.resourceKey=**/exception/**/*.java
sonar.issue.ignore.multicriteria.s1068clientdto.ruleKey=java:S1068
sonar.issue.ignore.multicriteria.s1068clientdto.resourceKey=**/client/dto/**/*.java
sonar.host.url=http://localhost:9000
