sonar.projectKey=flowboard-board-service
sonar.projectName=FlowBoard Board Service
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.test.inclusions=src/test/java/**/*.java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.junit.reportPaths=target/surefire-reports
sonar.exclusions=**/target/**,**/.mvn/**,**/mvnw,**/mvnw.cmd
sonar.coverage.exclusions=src/main/java/com/flowboard/board/BoardServiceApplication.java,src/main/java/com/flowboard/board/client/CardClient.java,src/main/java/com/flowboard/board/client/ListClient.java,src/main/java/com/flowboard/board/client/WorkspaceClient.java,src/main/java/com/flowboard/board/config/RabbitMQConfig.java,src/main/java/com/flowboard/board/config/SecurityConfig.java,src/main/java/com/flowboard/board/dto/BoardResponse.java,src/main/java/com/flowboard/board/dto/PublicBoardDetailResponse.java,src/main/java/com/flowboard/board/dto/PublicCardClientResponse.java,src/main/java/com/flowboard/board/dto/PublicListClientResponse.java,src/main/java/com/flowboard/board/dto/SendNotificationRequest.java,src/main/java/com/flowboard/board/dto/UpdateBoardMemberRoleRequest.java,src/main/java/com/flowboard/board/dto/UpdateBoardRequest.java,src/main/java/com/flowboard/board/dto/WorkspaceMemberResponse.java,src/main/java/com/flowboard/board/dto/WorkspaceResponse.java,src/main/java/com/flowboard/board/entity/Board.java,src/main/java/com/flowboard/board/entity/BoardMember.java,src/main/java/com/flowboard/board/entity/BoardMemberRole.java,src/main/java/com/flowboard/board/entity/BoardPriority.java,src/main/java/com/flowboard/board/exception/ErrorResponse.java,src/main/java/com/flowboard/board/repository/BoardMemberRepository.java,src/main/java/com/flowboard/board/repository/BoardRepository.java,src/main/java/com/flowboard/board/service/BoardService.java,src/main/java/com/flowboard/board/service/BoardServiceImpl.java
sonar.issue.ignore.multicriteria=s1068dto,s1068entity,s1068exception,s1068clientdto
sonar.issue.ignore.multicriteria.s1068dto.ruleKey=java:S1068
sonar.issue.ignore.multicriteria.s1068dto.resourceKey=**/dto/**/*.java
sonar.issue.ignore.multicriteria.s1068entity.ruleKey=java:S1068
sonar.issue.ignore.multicriteria.s1068entity.resourceKey=**/entity/**/*.java
sonar.issue.ignore.multicriteria.s1068exception.ruleKey=java:S1068
sonar.issue.ignore.multicriteria.s1068exception.resourceKey=**/exception/**/*.java
sonar.issue.ignore.multicriteria.s1068clientdto.ruleKey=java:S1068
sonar.issue.ignore.multicriteria.s1068clientdto.resourceKey=**/client/dto/**/*.java
sonar.host.url=http://localhost:9000
